# /docker/Dockerfile.ocr
FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends libheif-dev gcc libheif1 heif-gdk-pixbuf netcat-traditional

WORKDIR /app

ENV PYTHONPATH "${PYTHONPATH}:/app/src"

COPY docker/requirements_ocr.txt /tmp/requirements_ocr.txt
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r /tmp/requirements_ocr.txt

COPY src /app/src