# docker/Dockerfile.streamlit
FROM python:3.10-slim

WORKDIR /app

COPY docker/requirements_streamlit.txt /tmp/requirements_streamlit.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements_streamlit.txt

COPY src/services/streamlit_app /app/streamlit_app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/main_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
